"""add reviews relationship

Revision ID: 9d3ba6a173a8
Revises: 3f69a04b687c
Create Date: 2025-09-04 14:07:13.592917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3ba6a173a8'
down_revision: Union[str, Sequence[str], None] = '3f69a04b687c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_reviews', sa.Column('reviewer_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('recipe_reviews_user_id_fkey'), 'recipe_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_reviews', 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('recipe_reviews', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_reviews', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recipe_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('recipe_reviews_user_id_fkey'), 'recipe_reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('recipe_reviews', 'reviewer_id')
    # ### end Alembic commands ###
